[project]
name = "cipher"
version = "0.0.1"
description = "A simple encryption/decryption tool"
authors = [{ name = "sean1832" }]
license = { text = "MIT" }
dependencies = ["cryptography", "pyqt6"]

[project.scripts]
cipher = "cipher.cli:main"
cipher-gui = "cipher.gui:main"
